name: Action CodeQL
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['java']
        version: ['8.0.261'] 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        config-file: ./.github/codeql/codeql-config.yml
        languages: ${{ matrix.language }}
        
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}

    # Autobuild attempts to build any compiled languages in this case Java
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1



    #- run: |
    #   make bootstrap
    #   make release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v
